cmake_minimum_required(VERSION 3.21)
project(stereo-madness-welcome VERSION 1.0.0)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_subdirectory(${GEODE_SDK} ${CMAKE_CURRENT_BINARY_DIR}/geode)

file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS src/*.cpp)

geode_mod(${PROJECT_NAME} SOURCES ${SOURCES})
